# Generated by Django 2.2.7 on 2019-11-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMP3297', '0002_auto_20191123_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerordeveloper',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
